### ISSUE TITLE
yxdb-utils-0.1.0.0 release tarball is broken

### ISSUE THREAD

**Issue by peti** [MichaelBurge/yxdb-utils#2]
According to http://hydra.cryp.to/build/805973/log/raw, the modules `Tests.Data.Binary.C`, `Tests.Codec.Compression.LZF.ByteString`, and `Tests.Database.Alteryx` are missing from the tarball since they cannot be found while trying to compile the test suite.

**Comment by MichaelBurge** [comment]
Hi @peti,

Thanks for catching this. I've included the test modules and data in a new Hackage release, and ran the following commands in a directory extracted from the tarball to ensure that the tests pass:
$ cabal install --only-dependencies --enable-tests -j8
$ cabal configure --enable-tests
$ cabal build
$ cabal test
